### ISSUE TITLE
Deprecated selector in `gfm-todotxt/index.less`

### ISSUE THREAD

**Issue by calebgrove** [jronallo/gfm-todotxt#1]
In `gfm-todotxt/index.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow .gfm-todotxt.due` => `atom-text-editor.editor .syntax--gfm-todotxt.syntax--due`

* `atom-text-editor::shadow .gfm-todotxt.list` => `atom-text-editor.editor .syntax--gfm-todotxt.syntax--list`

* `atom-text-editor::shadow .gfm-todotxt.list-today` => `atom-text-editor.editor .syntax--gfm-todotxt.syntax--list-today`

* `atom-text-editor::shadow .gfm-todotxt.list-done` => `atom-text-editor.editor .syntax--gfm-todotxt.syntax--list-done`

* `atom-text-editor::shadow .gfm-todotxt.ykk` => `atom-text-editor.editor .syntax--gfm-todotxt.syntax--ykk`

* `atom-text-editor::shadow .gfm-todotxt.dotnote,
atom-text-editor::shadow .gfm-todotxt.dothandout` => `atom-text-editor.editor .syntax--gfm-todotxt.syntax--dotnote,
atom-text-editor.editor .syntax--gfm-todotxt.syntax--dothandout`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by jronallo** [comment]
This should be resolved in the latest release.
